# Environment file for LLM Fingerprinting project
name: llm-fp
channels:
  - conda-forge
dependencies:
  - ftfy
  - huggingface_hub
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - python=3.12
  - pytorch
  - pywavelets
  - rapidfuzz
  - regex
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - wordfreq
  # dev tooling
  - black
  - coverage
  - hatchling
  - mypy
  - pre-commit
  - pytest
  - pytest-cov
  - ruff
